### ISSUE TITLE
Aetherial Wheel Stand

### ISSUE THREAD

**Issue by V3semir** [Ottermandias/Accountant#1]
Hi! Is it possible to add the Wheel timer to the plugin? It would be very handy!

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/141462891-a0108706-eb64-4144-9da0-55f9d98b9929.png)

**Comment by Ottermandias** [comment]
Currently refactoring a bunch, will take a while, but yeah.

**Comment by V3semir** [comment]
Heck yeah, thank you!
