### ISSUE TITLE
Mini Cactpot / Jumbo Cactpot incorrectly colored as "some objects underway"

### ISSUE THREAD

**Issue by BeetleLord** [Ottermandias/Accountant#14]
When Mini Cactpot and Jumbo Cactpot are at 0/3 tickets remaining, they are incorrectly considered to be in a state of "some objects underway," and therefore will never show up with the color of "all objects underway."

**Comment by Ottermandias** [comment]
Do you have multiple characters listed? Because that's not the case for me.

**Comment by BeetleLord** [comment]
No, I do not have multiple characters listed.

**Comment by codyhatch** [comment]
I have the same issue. ![image](https://user-images.githubusercontent.com/1132365/147891547-c855eaeb-65d0-4c77-a739-1111e014b195.png)

Here I only have one character, and they have purchased all mini/jumbo Cactpot tickets. That doesn't seem like how it should work....?

**Comment by Ottermandias** [comment]
Should be fixed now.
