### ISSUE TITLE
Tasks header always using default header color

### ISSUE THREAD

**Issue by BeetleLord** [Ottermandias/Accountant#15]
The Tasks header remains as the Default Header color, regardless of the state of any currently tracked Tasks, such as levequests near/at cap.

**Comment by Ottermandias** [comment]
This is by design.

**Comment by BeetleLord** [comment]
I see. Not a bug then, but might I ask why?

**Comment by Ottermandias** [comment]
Because the colors for the different tasks are a bit inconsistent and I couldn't really think of a consistent way to fuse them into a global color that would fit.

**Comment by BeetleLord** [comment]
I have pondered this a bit... how about new settings for "all tasks complete," "some tasks complete," and "no tasks complete"? This would at least allow the header of the tasks section to behave consistently with all of the other categories.
