### ISSUE TITLE
Crops header incorrectly colored as "some crops wilted"

### ISSUE THREAD

**Issue by BeetleLord** [Ottermandias/Accountant#17]
Today, I noticed that the crops header was incorrectly colored as "some crops wilted" when, in fact, no crops were wilted. None of the plants were considered to be in a wilted state by the addon either.

I noticed that once I had harvested and replanted all of my fully-grown crops, the issue disappeared. This leads me to believe that the addon is, in some cases, incorrectly considering fully-grown crops as wilted, for the purposes of determining the header color. Probably because they have not been watered recently and would be wilted if not in a fully-grown state.

**Comment by Ottermandias** [comment]
I think I fixed that case for Withered, but I might have overlooked fixing it for Wilted too. I'll look into it, thanks!
