### ISSUE TITLE
[6.01] Accountant isn't picking up Submersible timers

### ISSUE THREAD

**Issue by Felys1998** [Ottermandias/Accountant#19]
My submarines that I sent out today post-patch are not updating in Accountant with their new timers. I haven't been able to confirm if others are experiencing the same issue. Also don't know how to get additional info to troubleshoot but if I can help in any way let me know.

**Comment by Ottermandias** [comment]
Sub and airship timers are based on network opcodes which required an update of Accountant (this time), the update was merged  about 9 hours ago. Did you update Accountant since then?

**Comment by Felys1998** [comment]
Just picked up the new version this morning on my daily re-log, Timers are now picking up. Thanks, now I know :)
