### ISSUE TITLE
Crops not updating to "Grown Out" when planted before adding the plugin

### ISSUE THREAD

**Issue by rekyuu** [Ottermandias/Accountant#23]
Hi there!

I planted some Tantaplant seeds a few days before installing the plugin, and since I can't tend to them anymore the plugin thinks they are wilting.

![image](https://user-images.githubusercontent.com/14059899/147862131-5d7390c5-3105-4b7e-98e0-fbacb49137d8.png)

Not sure if this is related to #17 or #18, so I thought I'd make a new issue just in case. Maybe a check to see if interacting with the bed shows that the plant is ready for harvest?

Thank you!

**Comment by Ottermandias** [comment]
EIther just harvest them, or if you intend to keep them grown out, you'd be better of deleting them in the settings. Otherwise your Crops header would always be green, too. Since they're grown out, they'll never be added again.

**Comment by rekyuu** [comment]
Okay, I did in fact delete their entries as they're gonna stay there forever for onion farming. Good to know though, appreciate it!
