### ISSUE TITLE
Crop timers?

### ISSUE THREAD

**Issue by CharonM72** [Ottermandias/Accountant#3]
Hello, I see that Accountant has a setting for crop timers, but I don't see my crop beds show up in there. I have crop timers enabled, and the plots added to the Plot Names list. Am I doing something wrong?

Thank you.

**Comment by Ottermandias** [comment]
You need to interact with crops for them to show up (tending/planting). If you have done that and they did not appear, what's your client language?

**Comment by CharonM72** [comment]
Yes I've done that and they don't show up.

I suppose it may be related to the language yeah... I play in English and Japanese simultaneously (thanks to an XIVAlexander feature). So crop names show up in both English and Japanese...

**Comment by Ottermandias** [comment]
Both in the original game interface? If not, which one is in the actual dialogue boxes? I can't read Japanese so the matching and parsing functions may be off for japanese dialogue.
If the feature changes the original game interface text completely, you're fucked anyway. :D

**Comment by CharonM72** [comment]
Yeah... they're displayed like this:

![image](https://user-images.githubusercontent.com/1299220/143326567-f9df04c8-3a2c-43ee-80e1-692790669a4f.png)

I may be able to put an exception into the script that converts their names. I've had to do that before anyway.

**Comment by Ottermandias** [comment]
Think this is something you have to solve on your side, I'll close this for now.
