### ISSUE TITLE
Outside Crops Bed/Patch incorrect when using german language

### ISSUE THREAD

**Issue by GarnetKatz** [Ottermandias/Accountant#35]
It seems like the currect version of the plugin confuses beds and patches, causing plants to be outside the limit of 3 patches and therefore not displayed.

Steps to reproduce:
1. Delete all current crop data.
2. Enter a plot in the config that has 3 deluxe patches with 8 beds each.
3. Tend to the crop in patch 1 bed 8:
->Expected: The Accountant interface should now show a new entry on your plot with bed 1-8 and the crop.
-> What actually happens: Nothing. My guess: An attempt was made to enter patch 8 bed 3 which is outside the boundaries.
4. Tend to the crop in patch 2. bed 1:
-> Expectation: The accountant interface should now show a new entry on your plot with bed 2-1 and the crop.
-> What actually happens: The accountant interface does create the plot, but it shows the crop in bed 1-2 instead of 2-1.
5. Tend to all crops
-> Expectation: The accountant interface should now show every crop.
-> The accountant interface actually shows only beds 1-1 to 1-3, 2-1 to 2-3, and 3-1 to 3-3.

The same can be reproduced on plots that only have 2 patches.
In this case, accountant will only show 1-1 to 1-2, and 2-1 to 2-2.

**Comment by GarnetKatz** [comment]
This only happens when not using English as game language, in my case german. 
As soon as i do the same in english, it just works as intended.

**Comment by Ottermandias** [comment]
Did the order put to the selectable list change for german? Because to my knowledge I had the orders all right for all 4 languages.

**Comment by GarnetKatz** [comment]
> Did the order put to the selectable list change for german? Because to my knowledge I had the orders all right for all 4 languages.

Unfortunately, I don't know how to check this. I don't know anything about it, but it sounds conclusive. 
Changed the language back to German and the problem is back, as suspected. 
If I can help you in any way, let me know. And thanks for the otherwise great plugin.

**Comment by Ottermandias** [comment]
Hm, I might just have had them mixed up. Really, no german user ever reported that before? Weird.
Or SE had them the wrong way around and fixed that now, also a possibility when considering how ward/plot numbers are inverted this patch :D

**Comment by GarnetKatz** [comment]
I guess so. Anyway, thanks for reacting and coming up with a solution so fast.
Do you have any idea when you will put it up on Dalamud, or update the .zip? 
Thanks again!
