### ISSUE TITLE
Fake Airship missions appeared

### ISSUE THREAD

**Issue by Spazzze** [Ottermandias/Accountant#37]
Hi! 
Thanks for your work I am using your plugin for a couple of month already :)
Today (after patch?) I've got some fake airship missions at my tracker.
I dont have airships at my FC at all, may be some debug kept enabled?

![image](https://user-images.githubusercontent.com/8989548/170070039-dfab5212-de54-4e7b-ab70-3f2a7db99d02.png)

**Comment by Ottermandias** [comment]
Opcodes.
