### ISSUE TITLE
No longer updating crops

### ISSUE THREAD

**Issue by allainecactuar** [Ottermandias/Accountant#39]
Sometime in the last 12 hours Accountant stopped updating crop information. I noticed when it claimed plants were withering that were not, and after watering them nothing changed. I have restarted the game and ensured that everything is up to date. I tried deleting all the crop entries in Accountant and now they're just not getting added back. Submersible, Retainer, and Map timers are all still working.

**Comment by allainecactuar** [comment]
Checked the xldev logs, and there is one warning of unknown interest but also some errors from Accountant: 


09:04:15.467 | WRN [XivCommon] [XIVCommon] Could not find signature for Examine. This functionality will be disabled.
--------------------------------
09:06:36.332 | ERR [Accountant] Housing Zone 0 should not be able to have crops.
--------------------------------
09:06:40.153 | ERR [Accountant] Housing Zone 0 should not be able to have crops.
--------------------------------
09:07:43.800 | ERR [Accountant] Housing Zone 0 should not be able to have crops.
--------------------------------
09:07:44.814 | ERR [Accountant] Housing Zone 0 should not be able to have crops.
--------------------------------
09:07:45.787 | ERR [Accountant] Housing Zone 0 should not be able to have crops.
--------------------------------
09:07:47.347 | ERR [Accountant] Housing Zone 0 should not be able to have crops.
--------------------------------
09:07:48.361 | ERR [Accountant] Housing Zone 0 should not be able to have crops.
--------------------------------
09:09:49.021 | ERR [Accountant] Housing Zone 0 should not be able to have crops.
--------------------------------
09:09:55.471 | ERR [Accountant] Housing Zone 0 should not be able to have crops.
--------------------------------
09:10:03.178 | ERR [Accountant] Housing Zone 0 should not be able to have crops.

**Comment by Ottermandias** [comment]
Dalamud issue.
