### ISSUE TITLE
Crop Timer

### ISSUE THREAD

**Issue by spval** [Ottermandias/Accountant#4]
Fertilizing doesn't update the finished time, and an additional timer for fertilization would be lovely too.

**Comment by Ottermandias** [comment]
Fertilization is a useless waste of time and I can't incorporate other people fertilizing anyway, so I don't bother. Also, the mechanism by which fertilization reduces remaining time is not 100% understood (though it probably is 1% off of the remaining time or something similar)

**Comment by spval** [comment]
I do it frequently so thank you for insulting me and my time.

**Comment by Ottermandias** [comment]
I did neither insult you nor your time. I don't judge you for deciding to waste it. That does not make it not a waste, though.
Feel free to make a PR if you want it.
