### ISSUE TITLE
Crop completion notification time differs from actual

### ISSUE THREAD

**Issue by rib3ru** [Ottermandias/Accountant#47]
In the Japanese-language environment, the Althyk Lavender Seeds(JP name:アルジクラベンダーの種) completion notification is appear earlier than it actually is. (It is not actually completed.)

Althyk Lavender Seeds bear fruit in 24 hours, but if you take care of them right after planting in the field, the UI will show 21:59!

Perhaps other species may have different times. (Haven't checked yet.)

**Comment by Ottermandias** [comment]
Althyk lavender grows out in 22 hours (+ up to 63 minutes for the ward timer). They do not actually take 24 hours.
