### ISSUE TITLE
Map allowance not updated when looting map

### ISSUE THREAD

**Issue by YsEmei** [Ottermandias/Accountant#63]
Map allowance isn't updated when you pick a treasure map. You have to open Timers window for it to refresh.
I have only tried on the new maps. Not sure if old maps still refresh like before when you pick them.

**Comment by Ottermandias** [comment]
Do you have gathering messages filtered? I added the map already, and it works for me, but it was still using the old method that would not receive messages that another plugin filters to parse them.
Changing that now.

**Comment by YsEmei** [comment]
I do have NoSoliciting to filter some chat. That might be it.

**Comment by YsEmei** [comment]
Works in newest version. Thank you

**Comment by YsEmei** [comment]
I have the same issue with Crops timer. Can it be the same problem?

![image](https://github.com/user-attachments/assets/dafb0bf4-6e5a-463b-8fc5-d4ce698ac707)
