### ISSUE TITLE
Crop timer doesn't recognize the outdoor crop in CN version

### ISSUE THREAD

**Issue by curatorjin** [Ottermandias/Accountant#69]
planting/tending can't record the crop or the bed outside,
while indoor pot can be recognized correctly.
![image](https://github.com/user-attachments/assets/46b65b46-9045-41e0-b502-b8ca4ac16341)

**Comment by Ottermandias** [comment]
The CN version is on a different game version that I do not have access to. It is not supported. Use one of the CN-specific forks, if they exist.
