### ISSUE TITLE
Aetherial Wheel not detected in french

### ISSUE THREAD

**Issue by Hiroa** [Ottermandias/Accountant#7]
Hey! 
Aetherial wheels don't seem to be detected when the game langage is set to french.
![Screenshot_2](https://user-images.githubusercontent.com/3938368/143779649-aaafe83f-8e72-4969-8883-3ff75200e1f1.png)

The wheel is detected when I set my game in english but when I set it back in french, the text encoding seem to have some issue.
![Screenshot_1](https://user-images.githubusercontent.com/3938368/143779752-f1b29aaa-2c66-4806-a5a1-e1dacd50991a.png)

**Comment by Ottermandias** [comment]
Should be fixed in the next release.

**Comment by Hiroa** [comment]
It's working perfectly. Thank you!
![Screenshot_1](https://user-images.githubusercontent.com/3938368/145353259-5874c91b-cc9b-4085-9126-bba20b06627a.png)
