### ISSUE TITLE
[Request] Add a toggle to NOT apply colours to the collapsed header

### ISSUE THREAD

**Issue by cglatot** [Ottermandias/Accountant#8]
Hi - I would like to see a setting somewhere in this so that the header does NOT take any styling when it is collapsed.

You can see an example of what I mean here: 
![image](https://user-images.githubusercontent.com/10439257/144052962-210b6e70-8cec-4132-97b0-dc606d3a9675.png)

Accountant Timers has a colourised header, and when crops are growing it can be blue, or whatever colour. You can also see that above accountant is another plugin "Yes Already" which uses the default Dalamud style and colouring. ALL of the plugins that I have via dalamud use the dalmud styling for collapsed.

Can you please add a toggle so that your styles do NOT overwrite the header? I would like it to inherit the default dalamud style. Even when there are no crop timers.

Thanks in advance!

**Comment by Ottermandias** [comment]
Done in the next release.
